# Generated by Django 4.2.4 on 2023-08-12 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.CharField(max_length=255)),
                ('event_rules', models.TextField()),
                ('min_members', models.IntegerField(default=1)),
                ('max_members', models.IntegerField(default=1)),
                ('prize_worth', models.IntegerField()),
                ('online', models.BooleanField(default=True)),
                ('image', models.ImageField(default='event_default.png', upload_to='image_uploads/event_pics/')),
                ('showPeformanceLink', models.BooleanField(default=True)),
                ('portalUrl', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompTeam',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name1', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=127)),
                ('module_query_name_without_spaces_all_small', models.CharField(max_length=127)),
                ('module_icon', models.ImageField(default='module_icon_default.png', upload_to='image_uploads/moduleicons/')),
                ('module_icon_active', models.ImageField(default='module_icon_default.png', upload_to='image_uploads/moduleicons/active/')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name2', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteams2', to='competitions.compteam')),
            ],
        ),
    ]
