# Generated by Django 4.2.4 on 2023-08-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteam',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compteam',
            name='members',
            field=models.ManyToManyField(to='users.teammembers'),
        ),
        migrations.AddField(
            model_name='competition',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulename', to='competitions.module'),
        ),
    ]
