# Generated by Django 4.2.4 on 2023-11-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeCompetition', models.CharField(max_length=50)),
                ('solo_or_group', models.CharField(max_length=10)),
            ],
        ),
    ]
