# Generated by Django 4.2.4 on 2023-12-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_allcompetition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allCompetition',
        ),
        migrations.AddField(
            model_name='competition',
            name='solo_or_group',
            field=models.CharField(default='', max_length=10),
        ),
    ]
