# Generated by Django 4.2.6 on 2023-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_delete_allcompetition_competition_solo_or_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event_desc',
            field=models.CharField(max_length=500),
        ),
    ]
