# Generated by Django 4.2.6 on 2023-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize_worth',
            field=models.CharField(max_length=255),
        ),
    ]
