# Generated by Django 4.2.6 on 2023-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_event_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
