# Generated by Django 4.2.6 on 2023-12-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteam',
            name='team_name',
            field=models.CharField(default='undefined', max_length=255),
        ),
    ]
