# Generated by Django 4.2.4 on 2023-08-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=20)),
                ('alcherid', models.CharField(blank=True, max_length=255, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='user-default.png', upload_to='image_uploads/userdp/')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('collegename', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=14)),
                ('alternate_phone', models.CharField(blank=True, max_length=14)),
                ('team_members', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.CharField(default='email', max_length=200)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('events_registered', models.ManyToManyField(blank=True, related_name='competition', to='competitions.competition')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('interest', models.ManyToManyField(related_name='interest', to='competitions.module')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('memberid', models.CharField(default='MEM-XXXX-XXXX', max_length=255)),
                ('img', models.ImageField(default='user-default.png', upload_to='image_uploads/userdp/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('accomodation', models.BooleanField(blank=True, default=False)),
                ('daysStay', models.IntegerField(default=0)),
                ('accomodation_type', models.CharField(default='none', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('blankets', models.IntegerField(default=0)),
                ('dues', models.IntegerField(default=0)),
                ('Accomodation', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('totalPaid', models.IntegerField(default=0)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to='users.teammembers')),
            ],
        ),
    ]
