# Generated by Django 4.2.4 on 2023-11-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="img",
            field=models.ImageField(
                default="default.jpg", upload_to="image_uploads/userdp/"
            ),
        ),
    ]
