# Generated by Django 4.2.4 on 2023-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(default='user-default.png', upload_to='image_uploads/userdp/'),
        ),
    ]
