# Generated by Django 4.2.4 on 2023-12-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_newuser_phone_number_newuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='teamname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
