# Generated by Django 4.2.4 on 2023-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_newuser_teamname"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="state",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
