# Generated by Django 4.2.6 on 2023-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teammembers_gender_alter_teammembers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
