# Generated by Django 4.2.6 on 2023-12-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_teammembers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='teamname',
        ),
    ]
