# Generated by Django 4.2.6 on 2024-02-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='name1')),
                ('email1', models.CharField(max_length=100, verbose_name='email1')),
                ('contact1', models.IntegerField(verbose_name='contact1')),
                ('squad', models.CharField(max_length=20, verbose_name='squad')),
                ('language', models.CharField(max_length=4, verbose_name='language')),
            ],
        ),
    ]
